mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

mysite/polls/urls.py
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url


app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'home', views.home, name='home'),
    url(r'^about', views.about, name='about'),
    url(r'login/', views.user_login, name='login'),
    url(r'^logout', views.logout_view, name='logout'),
    url(r'^logout-then-login$', auth_views.logout_then_login, name='logout_then_login'),
    url(r'dash', views.dashboard, name='dashboard'),
    url(r'^register$', views.register, name='register'),
]

mysite/polls/models.py
from django.db import models
import datetime

from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        was_published_recently.admin_order_field = 'pub_date'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from .models import Choice, Question
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import LoginForm, UserRegistrationForm
from django.contrib import messages


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "Ты не выбрал вариант.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))


def home(request):
    return render(request, 'polls/home.html')


def about(request):
    return render(request, 'polls/about.html')


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, 'polls/dashboard.html')
                else:
                    return HttpResponse('Disabled account')
            else:
                messages.error(request, 'username or password not correct')
                return redirect('http://127.0.0.1:8000/login/')
    else:
        form = LoginForm()
    return render(request, 'polls/login.html', {'form': form})


@login_required
def dashboard(request):
    return render(request, 'polls/dashboard.html', {'section': 'dashboard'})


def logout_view(request):
    logout(request)
    return redirect('http://127.0.0.1:8000/home')


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'polls/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'polls/register.html', {'user_form': user_form})

mysite/polls/templates/polls/about.html
{% extends 'polls/base.html' %}
{% block title %} О нас {% endblock %}
{% block content %} Здесь вы можете видеть информацию о компании {% endblock %}

mysite/polls/templates/polls/base.html
<!doctype html>
<html lang=ru>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">Household partnerships</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'polls:home' %}">Главная</a>
        <a class="p-2 text-dark" href="{% url 'polls:about' %}">О нас</a>
        <a class="p-2 text-dark" href="{% url 'polls:index' %}">Голосования</a>
        {% if request.user.is_anonymous %}
        <a class="btn btn-outline-primary" href="{% url 'polls:login' %}">Log in</a>
        <a class="btn btn-outline-primary" href="{% url 'polls:register' %}">Sign up</a>
        {% endif %}
        <span class="user">
        {% if request.user.is_authenticated %}
            Hello {{ request.user.first_name }},
            <a href="{% url 'polls:logout' %}">Logout</a>

        {% endif %}
    </span>

    </nav>

</div>
<div id="header">

    {% if request.user.is_authenticated %}
    <ul class="menu">
    </ul>
    {% endif %}


</div>
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
</html>

mysite/polls/templates/polls/dashboard.html
{% extends "polls/base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <h1>Dashboard</h1>
    <p>Welcome to your dashboard.</p>
{% endblock %}

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/home.html
{% extends 'polls/base.html' %}
{% block title %} Главная страница {% endblock %}
{% block content %}Здесь находится самая главная страница ин зе ворлд{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block title %} Голосования {% endblock %}

{% block content %}<div class="container">
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>
{% endblock %}

mysite/polls/templates/polls/logged_out.html
{% extends "polls/base.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
    <h1>Logged out</h1>
    <p>You have been successfully logged out. You can <a href="{% url 'polls:login' %}">log-in again</a>.</p>
{% endblock %}

mysite/polls/templates/polls/login.html
{% extends "polls/base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}
<h1>Log-in</h1>
<p>Please, use the following form to log-in:</p>
<form action="" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Log-in"></p>
</form>
{% for message in messages %}

<div class="alert alert-success">
    <a class="close" href="#" data-dismiss="alert">×</a>

    {{ message }}

</div>
{% endfor %}
{% endblock %}

mysite/polls/templates/polls/register.html
{% extends "polls/base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}
    <h1>Create an account</h1>
    <p>Please, sign up using the following form:</p>
    <form action="register" method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Create my account"></p>
    </form>
{% endblock %}

mysite/polls/templates/polls/register_done.html
{% extends "polls/base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1>Welcome {{ new_user.first_name }}!</h1>
    <p>Your account has been successfully created. Now you can <a href="{% url 'polls:login' %}">log in</a>.</p>
{% endblock %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:home' %}">На главную</a>